/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserProjectCreateNestedManyWithoutUsersInput } from "./UserProjectCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { TaskCreateNestedManyWithoutUsersInput } from "./TaskCreateNestedManyWithoutUsersInput";
import { UserTaskCreateNestedManyWithoutUsersInput } from "./UserTaskCreateNestedManyWithoutUsersInput";
import { RoleWhereUniqueInput } from "../../role/base/RoleWhereUniqueInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserProjectCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserProjectCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserProjectCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userProjects?: UserProjectCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserTaskCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserTaskCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserTaskCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userTasks?: UserTaskCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => RoleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoleWhereUniqueInput)
  @IsOptional()
  @Field(() => RoleWhereUniqueInput, {
    nullable: true,
  })
  role?: RoleWhereUniqueInput | null;
}

export { UserCreateInput as UserCreateInput };
